Pin specific version of Jinja2
Before this change, the docs failed to build with the following
error:

ImportError: cannot import name 'environmentfilter' from 'jinja2'

A fix to this problem is to explicitly pin Jinja2 version.

(cherry picked from commit cdaf75a6cf54b91f3f795aa509cf836166dad1e2)