Make ccmRule `static final`
This suit was intermitently failing with following errors:
```
PreparedStatementCachingIT.should_invalidate_cache_entry_on_basic_udt_change_result_set » IllegalState Attempting to use a Ccm rule while another is in use.  This is disallowed
Error:    PreparedStatementCachingIT.should_invalidate_cache_entry_on_basic_udt_change_variable_defs » Runtime The command '[ccm, create, ccm_1, -i, 127.0.0., -n, 1:0, -v, release:6.1.1, --scylla, --config-dir=/tmp/ccm2069125928025678067]' failed to execute
```
Due to the attempts to use ccmRule in parallel.