Use AttributeKey.valueOf instead of AttributeKey.newInstance.
AttributeKey.newInstance has been recently introduced and may cause NoSuchMethodErrors with older versions of Netty,
while AttributeKey.valueOf exists since at least Netty 4.0.23.Final - the version currently in use in Cassandra.